// src/components/Contact.jsx
import React from "react";
import Bounce from "react-reveal/Bounce";
import {
    Container,
    Row,
    UncontrolledTooltip
} from "reactstrap"

export default function Contact(props) {

    return (
        <div className="section section-typo section-padding-20" id="contact">
            <Container>
                <Bounce left>
                    <h1 className="title">Get in touch</h1>
                </Bounce>
                <div className="space-50" />
                <div>
                    <Bounce right>
                        <Row>

                            <a href="mailto:firzok.nadeem@gmail.com" id="mail">
                                <img
                                    alt="..."
                                    className="contact-icon"
                                    src={require("assets/img/gmail.png")}
                                />
                            </a>
                            <UncontrolledTooltip placement="top" target="mail" delay={0}>
                                Email Me
            				</UncontrolledTooltip>

                            <a href="https://github.com/firzok" id="git">
                                <img
                                    alt="..."
                                    className="contact-icon"
                                    src={require("assets/img/github-logo.png")}
                                />
                            </a>
                            <UncontrolledTooltip placement="top" target="git" delay={0}>
                                GitHub
            				</UncontrolledTooltip>

                            <a href="https://www.linkedin.com/in/firzok-nadeem/" id="linkedin">
                                <img
                                    alt="..."
                                    className="contact-icon"
                                    src={require("assets/img/linkedin.png")}
                                />
                            </a>
                            <UncontrolledTooltip placement="top" target="linkedin" delay={0}>
                                LinkedIn
            				</UncontrolledTooltip>

                            <a href="https://www.facebook.com/Firzoknadeem" id="fb">
                                <img
                                    alt="..."
                                    className="contact-icon"
                                    src={require("assets/img/facebook.png")}
                                />
                            </a>
                            <UncontrolledTooltip placement="top" target="fb" delay={0}>
                                Facebook
            				</UncontrolledTooltip>

                            <a href="https://www.instagram.com/ifirzok/" id="instagram">
                                <img
                                    alt="..."
                                    className="contact-icon"
                                    src={require("assets/img/instagram.png")}
                                />
                            </a>
                            <UncontrolledTooltip placement="top" target="instagram" delay={0}>
                                Instagram
            				</UncontrolledTooltip>

                            <a href="https://twitter.com/Firzok" id="twitter">
                                <img
                                    alt="..."
                                    className="contact-icon"
                                    src={require("assets/img/twitter.png")}
                                />
                            </a>
                            <UncontrolledTooltip placement="top" target="twitter" delay={0}>
                                Twitter
            				</UncontrolledTooltip>
                        </Row>
                        <div className="space-90"></div>
                    </Bounce>
                </div>
            </Container>


        </div>
    )
}

// src/components/Contact.vue
<template>
    <section id="contact" ref="contactSection" class="contact">
        <div class="title-row">
            <div
                class="title"
                :style="contactSectionInterpolator.title(proportion)"
            >
                Get in touch
            </div>
        </div>
        <div class="list">
            <div class="contact">
                <a href="mailto:firzok.nadeem@gmail.com">Email</a>
            </div>

            <div class="contact">
                <a href="https://www.linkedin.com/in/firzok-nadeem/"
                    >LinkedIn</a
                >
            </div>

            <div class="contact">
                <a href="https://github.com/firzok">GitHub</a>
            </div>

            <div class="contact">
                <a href="https://www.facebook.com/Firzoknadeem">Facebook</a>
            </div>

            <div class="contact">
                <a href="https://www.instagram.com/ifirzok/">Instagram</a>
            </div>

            <div class="contact">
                <a href="https://twitter.com/Firzok">Twitter</a>
            </div>
        </div>
    </section>
</template>

<script>
import { contactSectionInterpolator } from "./interpolators";
export default {
    name: "contact",
    components: {},
    props: {
        proportion: { type: Number, default: 0 },
    },
    data() {
        return { contactSectionInterpolator };
    },
    setup() {},
    methods: {},
    watch: {},
};
</script>

<style scoped lang="scss">
a,
a:hover,
a:focus,
a:active {
    text-decoration: none;
    color: inherit;
}

.contact {
    .title-row {
        overflow: hidden;

        .title {
            font-size: 5rem;
            font-weight: bold;
            text-transform: uppercase;
        }
    }
    .list {
        margin-left: 5rem;
        .contact {
            font-size: 2rem;
            margin: 2rem;
        }
    }
}
</style>
